import type { RecurrenceT, CountryT, CurrencyT } from 'src/donations/types';

const currencies: Array<CurrencyT> = [
  { code: 'usd', symbol: '$' },
  { code: 'eur', symbol: '€' },
];

const countries: Array<CountryT> = [
  { code: 0, name: 'Country' },
  { code: 1228, name: 'United States' },
  { code: 1001, name: 'Afghanistan' },
  { code: 1241, name: 'Åland Islands' },
  { code: 1002, name: 'Albania' },
  { code: 1003, name: 'Algeria' },
  { code: 1004, name: 'American Samoa' },
  { code: 1005, name: 'Andorra' },
  { code: 1006, name: 'Angola' },
  { code: 1007, name: 'Anguilla' },
  { code: 1008, name: 'Antarctica' },
  { code: 1009, name: 'Antigua and Barbuda' },
  { code: 1010, name: 'Argentina' },
  { code: 1011, name: 'Armenia' },
  { code: 1012, name: 'Aruba' },
  { code: 1013, name: 'Australia' },
  { code: 1014, name: 'Austria' },
  { code: 1015, name: 'Azerbaijan' },
  { code: 1212, name: 'Bahamas' },
  { code: 1016, name: 'Bahrain' },
  { code: 1017, name: 'Bangladesh' },
  { code: 1018, name: 'Barbados' },
  { code: 1019, name: 'Belarus' },
  { code: 1020, name: 'Belgium' },
  { code: 1021, name: 'Belize' },
  { code: 1022, name: 'Benin' },
  { code: 1023, name: 'Bermuda' },
  { code: 1024, name: 'Bhutan' },
  { code: 1025, name: 'Bolivia' },
  { code: 1250, name: 'Bonaire, Saint Eustatius and Saba' },
  { code: 1026, name: 'Bosnia and Herzegovina' },
  { code: 1027, name: 'Botswana' },
  { code: 1028, name: 'Bouvet Island' },
  { code: 1029, name: 'Brazil' },
  { code: 1030, name: 'British Indian Ocean Territory' },
  { code: 1032, name: 'Brunei Darussalam' },
  { code: 1033, name: 'Bulgaria' },
  { code: 1034, name: 'Burkina Faso' },
  { code: 1036, name: 'Burundi' },
  { code: 1037, name: 'Cambodia' },
  { code: 1038, name: 'Cameroon' },
  { code: 1039, name: 'Canada' },
  { code: 1040, name: 'Cape Verde' },
  { code: 1041, name: 'Cayman Islands' },
  { code: 1042, name: 'Central African Republic' },
  { code: 1043, name: 'Chad' },
  { code: 1044, name: 'Chile' },
  { code: 1045, name: 'China' },
  { code: 1046, name: 'Christmas Island' },
  { code: 1047, name: 'Cocos (Keeling) Islands' },
  { code: 1048, name: 'Colombia' },
  { code: 1049, name: 'Comoros' },
  { code: 1051, name: 'Congo, Republic of the' },
  { code: 1050, name: 'Congo, The Democratic Republic of the' },
  { code: 1052, name: 'Cook Islands' },
  { code: 1053, name: 'Costa Rica' },
  { code: 1054, name: 'Côte d’Ivoire' },
  { code: 1055, name: 'Croatia' },
  { code: 1056, name: 'Cuba' },
  { code: 1248, name: 'Curaçao' },
  { code: 1057, name: 'Cyprus' },
  { code: 1058, name: 'Czech Republic' },
  { code: 1059, name: 'Denmark' },
  { code: 1060, name: 'Djibouti' },
  { code: 1061, name: 'Dominica' },
  { code: 1062, name: 'Dominican Republic' },
  { code: 1064, name: 'Ecuador' },
  { code: 1065, name: 'Egypt' },
  { code: 1066, name: 'El Salvador' },
  { code: 1067, name: 'Equatorial Guinea' },
  { code: 1068, name: 'Eritrea' },
  { code: 1069, name: 'Estonia' },
  { code: 1070, name: 'Ethiopia' },
  { code: 1072, name: 'Falkland Islands (Malvinas)' },
  { code: 1073, name: 'Faroe Islands' },
  { code: 1074, name: 'Fiji' },
  { code: 1075, name: 'Finland' },
  { code: 1076, name: 'France' },
  { code: 1077, name: 'French Guiana' },
  { code: 1078, name: 'French Polynesia' },
  { code: 1079, name: 'French Southern Territories' },
  { code: 1080, name: 'Gabon' },
  { code: 1213, name: 'Gambia' },
  { code: 1081, name: 'Georgia' },
  { code: 1082, name: 'Germany' },
  { code: 1083, name: 'Ghana' },
  { code: 1084, name: 'Gibraltar' },
  { code: 1085, name: 'Greece' },
  { code: 1086, name: 'Greenland' },
  { code: 1087, name: 'Grenada' },
  { code: 1088, name: 'Guadeloupe' },
  { code: 1089, name: 'Guam' },
  { code: 1090, name: 'Guatemala' },
  { code: 1245, name: 'Guernsey' },
  { code: 1091, name: 'Guinea' },
  { code: 1092, name: 'Guinea-Bissau' },
  { code: 1093, name: 'Guyana' },
  { code: 1094, name: 'Haiti' },
  { code: 1095, name: 'Heard Island and McDonald Islands' },
  { code: 1096, name: 'Holy See (Vatican City State)' },
  { code: 1097, name: 'Honduras' },
  { code: 1098, name: 'Hong Kong' },
  { code: 1099, name: 'Hungary' },
  { code: 1100, name: 'Iceland' },
  { code: 1101, name: 'India' },
  { code: 1102, name: 'Indonesia' },
  { code: 1103, name: 'Iran, Islamic Republic Of' },
  { code: 1104, name: 'Iraq' },
  { code: 1105, name: 'Ireland' },
  { code: 1246, name: 'Isle of Man' },
  { code: 1106, name: 'Israel' },
  { code: 1107, name: 'Italy' },
  { code: 1108, name: 'Jamaica' },
  { code: 1109, name: 'Japan' },
  { code: 1244, name: 'Jersey' },
  { code: 1110, name: 'Jordan' },
  { code: 1111, name: 'Kazakhstan' },
  { code: 1112, name: 'Kenya' },
  { code: 1113, name: 'Kiribati' },
  { code: 1114, name: "Korea, Democratic People's Republic of" },
  { code: 1115, name: 'Korea, Republic of' },
  { code: 1251, name: 'Kosovo' },
  { code: 1116, name: 'Kuwait' },
  { code: 1117, name: 'Kyrgyzstan' },
  { code: 1118, name: "Lao People's Democratic Republic" },
  { code: 1119, name: 'Latvia' },
  { code: 1120, name: 'Lebanon' },
  { code: 1121, name: 'Lesotho' },
  { code: 1122, name: 'Liberia' },
  { code: 1123, name: 'Libya' },
  { code: 1124, name: 'Liechtenstein' },
  { code: 1125, name: 'Lithuania' },
  { code: 1126, name: 'Luxembourg' },
  { code: 1127, name: 'Macao' },
  { code: 1128, name: 'Macedonia, Republic Of' },
  { code: 1129, name: 'Madagascar' },
  { code: 1130, name: 'Malawi' },
  { code: 1131, name: 'Malaysia' },
  { code: 1132, name: 'Maldives' },
  { code: 1133, name: 'Mali' },
  { code: 1134, name: 'Malta' },
  { code: 1135, name: 'Marshall Islands' },
  { code: 1136, name: 'Martinique' },
  { code: 1137, name: 'Mauritania' },
  { code: 1138, name: 'Mauritius' },
  { code: 1139, name: 'Mayotte' },
  { code: 1140, name: 'Mexico' },
  { code: 1141, name: 'Micronesia, Federated States of' },
  { code: 1142, name: 'Moldova' },
  { code: 1143, name: 'Monaco' },
  { code: 1144, name: 'Mongolia' },
  { code: 1243, name: 'Montenegro' },
  { code: 1145, name: 'Montserrat' },
  { code: 1146, name: 'Morocco' },
  { code: 1147, name: 'Mozambique' },
  { code: 1035, name: 'Myanmar' },
  { code: 1148, name: 'Namibia' },
  { code: 1149, name: 'Nauru' },
  { code: 1150, name: 'Nepal' },
  { code: 1152, name: 'Netherlands' },
  { code: 1153, name: 'New Caledonia' },
  { code: 1154, name: 'New Zealand' },
  { code: 1155, name: 'Nicaragua' },
  { code: 1156, name: 'Niger' },
  { code: 1157, name: 'Nigeria' },
  { code: 1158, name: 'Niue' },
  { code: 1159, name: 'Norfolk Island' },
  { code: 1160, name: 'Northern Mariana Islands' },
  { code: 1161, name: 'Norway' },
  { code: 1162, name: 'Oman' },
  { code: 1163, name: 'Pakistan' },
  { code: 1164, name: 'Palau' },
  { code: 1165, name: 'Palestinian Territory' },
  { code: 1166, name: 'Panama' },
  { code: 1167, name: 'Papua New Guinea' },
  { code: 1168, name: 'Paraguay' },
  { code: 1169, name: 'Peru' },
  { code: 1170, name: 'Philippines' },
  { code: 1171, name: 'Pitcairn' },
  { code: 1172, name: 'Poland' },
  { code: 1173, name: 'Portugal' },
  { code: 1174, name: 'Puerto Rico' },
  { code: 1175, name: 'Qatar' },
  { code: 1179, name: 'Reunion' },
  { code: 1176, name: 'Romania' },
  { code: 1177, name: 'Russian Federation' },
  { code: 1178, name: 'Rwanda' },
  { code: 1252, name: 'Saint Barthélemy' },
  { code: 1180, name: 'Saint Helena' },
  { code: 1181, name: 'Saint Kitts and Nevis' },
  { code: 1182, name: 'Saint Lucia' },
  { code: 1253, name: 'Saint Martin (French part)' },
  { code: 1183, name: 'Saint Pierre and Miquelon' },
  { code: 1184, name: 'Saint Vincent and the Grenadines' },
  { code: 1185, name: 'Samoa' },
  { code: 1186, name: 'San Marino' },
  { code: 1207, name: 'Sao Tome and Principe' },
  { code: 1187, name: 'Saudi Arabia' },
  { code: 1188, name: 'Senegal' },
  { code: 1242, name: 'Serbia' },
  { code: 1238, name: 'Serbia and Montenegro' },
  { code: 1189, name: 'Seychelles' },
  { code: 1190, name: 'Sierra Leone' },
  { code: 1191, name: 'Singapore' },
  { code: 1249, name: 'Sint Maarten (Dutch Part)' },
  { code: 1192, name: 'Slovakia' },
  { code: 1193, name: 'Slovenia' },
  { code: 1194, name: 'Solomon Islands' },
  { code: 1195, name: 'Somalia' },
  { code: 1196, name: 'South Africa' },
  { code: 1197, name: 'South Georgia and the South Sandwich Islands' },
  { code: 1247, name: 'South Sudan' },
  { code: 1198, name: 'Spain' },
  { code: 1199, name: 'Sri Lanka' },
  { code: 1200, name: 'Sudan' },
  { code: 1201, name: 'Suriname' },
  { code: 1202, name: 'Svalbard and Jan Mayen' },
  { code: 1203, name: 'Swaziland' },
  { code: 1204, name: 'Sweden' },
  { code: 1205, name: 'Switzerland' },
  { code: 1206, name: 'Syrian Arab Republic' },
  { code: 1208, name: 'Taiwan' },
  { code: 1209, name: 'Tajikistan' },
  { code: 1210, name: 'Tanzania, United Republic of' },
  { code: 1211, name: 'Thailand' },
  { code: 1063, name: 'Timor-Leste' },
  { code: 1214, name: 'Togo' },
  { code: 1215, name: 'Tokelau' },
  { code: 1216, name: 'Tonga' },
  { code: 1217, name: 'Trinidad and Tobago' },
  { code: 1218, name: 'Tunisia' },
  { code: 1219, name: 'Turkey' },
  { code: 1220, name: 'Turkmenistan' },
  { code: 1221, name: 'Turks and Caicos Islands' },
  { code: 1222, name: 'Tuvalu' },
  { code: 1223, name: 'Uganda' },
  { code: 1224, name: 'Ukraine' },
  { code: 1225, name: 'United Arab Emirates' },
  { code: 1226, name: 'United Kingdom' },
  { code: 1227, name: 'United States Minor Outlying Islands' },
  { code: 1229, name: 'Uruguay' },
  { code: 1230, name: 'Uzbekistan' },
  { code: 1231, name: 'Vanuatu' },
  { code: 1232, name: 'Venezuela' },
  { code: 1233, name: 'Viet Nam' },
  { code: 1234, name: 'Virgin Islands, U.S.' },
  { code: 1031, name: 'Virgin Islands,British' },
  { code: 1235, name: 'Wallis and Futuna' },
  { code: 1236, name: 'Western Sahara' },
  { code: 1237, name: 'Yemen' },
  { code: 1239, name: 'Zambia' },
  { code: 1240, name: 'Zimbabwe' },
];

const months = {
  '0': '-- Month --',
  '1': '01 / Jan',
  '2': '02 / Feb',
  '3': '03 / Mar',
  '4': '04 / Apr',
  '5': '05 / May',
  '6': '06 / Jun',
  '7': '07 / Jul',
  '8': '08 / Aug',
  '9': '09 / Sep',
  '10': '10 / Oct',
  '11': '11 / Nov',
  '12': '12 / Dec',
};

let currentYear = new Date().getFullYear();
const years: any = {};
years[0] = '-- Year --';
for (var i = 1; i < 10; ++i) {
  years[currentYear + i] = '' + (currentYear + i);
}

export const Constants = {
  currencies,
  countries,
  months,
  years,
};

export const getCurrency = (currency: any) => {
  return (
    Constants.currencies.find((c) => c.code === currency) ??
    Constants.currencies[0]
  );
};

export const getCurrencyStr = (currency: CurrencyT, recurrence: RecurrenceT) =>
  currency.code.toUpperCase() + (recurrence === 'monthly' ? ' / mo' : '');

export default Constants;
