"""
Django settings for shared_goals project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)
ROOT_DIR = os.path.dirname(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]

# Application definition

INSTALLED_APPS = (
    [
        "corsheaders",
        "app",
        "donatetk.apps.DonationTkConfig",
    ]
    + (
        [
            "django.contrib.auth",
            "django.contrib.contenttypes",
        ]
        if "pytest" in sys.modules
        else []
    )
    + [
        "django.contrib.staticfiles",
        "django.contrib.humanize",
    ]
)

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CORS_URLS_REGEX = r"^/api/.*$"

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "app", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
            "libraries": {},
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': '127.0.0.1:11211',
#     }
# }

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# Logging settings
LOGGING = {
    "version": 1,
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": "/var/log/django-file.log",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "mail_admins"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
    "formatters": {
        "simple": {
            "format": "%(asctime)s donatetk: %(message)s",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": tuple(),
    "UNAUTHENTICATED_USER": None,
}

DONATETK_ORG_NAME = "Friends not Food"
DONATETK_WEBPAGE_HOST = os.environ["DONATETK_WEBPAGE_HOST"]
DONATETK_SEND_RECEIPT_EMAIL = True
DONATETK_STRIPE_TEST_PUBLIC_KEY = os.environ["DONATETK_STRIPE_TEST_PUBLIC_KEY"]
DONATETK_STRIPE_TEST_SECRET_KEY = os.environ["DONATETK_STRIPE_TEST_SECRET_KEY"]
DONATETK_STRIPE_LIVE_PUBLIC_KEY = os.environ["DONATETK_STRIPE_LIVE_PUBLIC_KEY"]
DONATETK_STRIPE_LIVE_SECRET_KEY = os.environ["DONATETK_STRIPE_LIVE_SECRET_KEY"]
DONATETK_STRIPE_ENDPOINT_SECRET = os.environ.get(
    "DONATETK_STRIPE_ENDPOINT_SECRET", None
)
DONATETK_STRIPE_LIVE_MODE = os.environ["DONATETK_STRIPE_LIVE_MODE"].lower() == "true"
